# Generated by Django 6.0.2 on 2026-03-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cooking_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select cooking time"),
                    ("< 15 min", "< 15 min"),
                    ("15-30 min", "15-30 min"),
                    (">30 min", ">30 min"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select difficulty"),
                    ("easy", "easy"),
                    ("medium", "medium"),
                    ("hard", "hard"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
