# Generated by Django 6.0.2 on 2026-03-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_add_cooking_time_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select difficulty"),
                    ("Easy", "Easy"),
                    ("Medium", "Medium"),
                    ("Hard", "Hard"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
